### PR TITLE
Request to resolve #301

### LINKED ISSUE #301: Change Treasury contracts from array to object
This is okay for now, and I know this isn't you, but I need to mention it. I don't like these variable names with indexes, the object below should not be an array, it should be an object with a unique key and we use that unique key here.

_Originally posted by @jessgusclark in https://github.com/RootstockCollective/dao-frontend/pull/298#discussion_r1820612177_

### PR DESCRIPTION
**Pull request by tzinadah**
Changed the variable treasuryContracts from an array to an object.

### CODE REVIEW

**Review by jessgusclark — CHANGES_REQUESTED** [review]
Thank you for your contribution into the repo, you are half way there. Changing the variable from an array to an object is only the first part. The second part is updating the references to it since it now is an object and those references were expecting an array.

**Comment by tzinadah** [comment]
References updated

**Review by rodrigoncalves — CHANGES_REQUESTED** [review]
Please check lint errors.

**Comment by tzinadah** [comment]
lint errors solved

**Review by rodrigoncalves — APPROVED** [review]
It works great! ✅

**Review by jessgusclark — APPROVED** [review]
Thanks for the fix!!

**Pull request merged**
