### PR TITLE
Add sorting functionality and refactor table components

### PR DESCRIPTION
**Pull request by shenshin**
Introduce sorting capabilities and custom renderers to the table component. Refactor the proposals table for better separation of data and presentation, and enhance the overall structure with new components for proposal name and status. Clean up ESLint configurations and improve type definitions.

### CODE REVIEW

**Comment by shenshin** [comment]
Screenshot 2024-12-03 at 05 42 46

**Comment by rodrigoncalves** [comment]
@shenshin please fix lint errors.

**Comment by shenshin** [comment]
Which errors? By the way , before starting working on this pr , I installed additional linting plugins. The app misses some very important linters such as eslint-plugin-react , react hooks and so on. But after finishing work I removed the modules because they should be better installed in a separate PR. So , I don't know what linting error you mean. Could you please give more details

**Comment by rodrigoncalves** [comment]
> Which errors? By the way , before starting working on this pr , I installed additional linting plugins. The app misses some very important linters such as eslint-plugin-react , react hooks and so on. But after finishing work I removed the modules because they should be better installed in a separate PR. So , I don't know what linting error you mean. Could you please give more details

https://github.com/RootstockCollective/dao-frontend/actions/runs/12143498097/job/33860517611?pr=445

**Review by rodrigoncalves — APPROVED** [review]
Looks good!

**Pull request merged**
