### PR TITLE
feat(dao): add feature flags

### PR DESCRIPTION
**Pull request by jurajpiar**
# What

Adds a feature flag system

# Why

To allow incremental delivery and feature-based testing, A/B testing, easier QA testing, linear history, less conflicting releases, ...

### CODE REVIEW

**Comment by jessgusclark** [comment]
In the description above, can you provide a small demo of how this would work? From what I can tell, it is part of the .env file as a variable set to _something_? And then from there how does a component or page know to show or not?

**Comment by jurajpiar** [comment]
> In the description above, can you provide a small demo of how this would work? From what I can tell, it is part of the .env file as a variable set to _something_? And then from there how does a component or page know to show or not?

Thanks, yes, I can attach a screen recording in a couple of hours.

**Comment by jurajpiar** [comment]
> > In the description above, can you provide a small demo of how this would work? From what I can tell, it is part of the .env file as a variable set to _something_? And then from there how does a component or page know to show or not?
> 
> Thanks, yes, I can attach a screen recording in a couple of hours.
> 
> but basically you just use it with `const { flags } = useFeatureFlags()`

here it is: https://rootstocklabs.slack.com/archives/C0540E911PA/p1730217831594049?thread_ts=1730217734.123399&cid=C0540E911PA

**Review by antomor — APPROVED** [review]
LGTM

**Pull request merged**
