### PR TITLE
DAO-707 LastBlock in the frontend implemented

### PR DESCRIPTION
**Pull request by Freshenext**

### CODE REVIEW

**Comment by jessgusclark** [comment]
@Freshenext This is missing a description so I can't help ya much. Is this dependeant on the new server changes that @sleyter93 did? If so, do we need a new/different .env file that uses that endpoint as the RIF Wallet Services?

**Comment by jessgusclark** [comment]
Nevermind, I just saw the next PR. I have merged that one, so we should be good here, but let's rebase to make sure.

**Comment by Freshenext** [comment]
> Nevermind, I just saw the next PR. I have merged that one, so we should be good here, but let's rebase to make sure.

This one is related to the change needed to show the proposals that were being truncated in the FE due to blockscout version 2 api. It's a change that I did in the backend to fetch using blockscout API V1, and now we can send the fromBlock, which will allow us to implement in the future some sort of pagination too.

**Review by jessgusclark — APPROVED** [review]
Proposals loaded much faster, thanks.

**Pull request merged**
